### PR TITLE
Version 0.7.2, switch to internal rapidjson, refresh recipe

### PR DESCRIPTION
**Pull request by dbast**
Refresh was done via selecting lines from `conda-skeleton pypi python-rapidjson`.

Using the package internal rapidjson lib was discussed already here https://github.com/conda-forge/python-rapidjson-feedstock/pull/15

### CODE REVIEW

**Comment by dbast** [comment]
Ready to merge :)

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
@SylvainCorlay @hajapy @itamarst @mariusvniekerk Can somebody please review this in context of https://github.com/conda-forge/python-rapidjson-feedstock/pull/15 thx.

**Comment by dbast** [comment]
This intentionally vendors a very specific version (via sha1 of submodule) of RapidJSON, which is self-contained and header-only).

**Comment by hajapy** [comment]
I think this is a reasonable solution until such as time as rapidjson has a new release that pyrj can rely on. Thanks for putting in the time to update the recipe!

**Review by hajapy — APPROVED** [review]
Looks good! My only comment would be that it might be nice to write a few tests beyond just the import test.

Also, a question: do we know if this will interact (clobber errors) with environments that also have rapidjson installed?

**Comment by dbast** [comment]
The content of locally build python-rapidjson-0.7.2-py36hf484d3e_0.tar.bz2:
```
.
├── info
│   ├── about.json
│   ├── files
│   ├── git
│   ├── hash_input.json
│   ├── index.json
│   ├── LICENSE.txt
│   ├── paths.json
│   ├── recipe
│   │   ├── conda_build_config.yaml
│   │   ├── meta.yaml
│   │   └── meta.yaml.template
│   └── test
│       └── run_test.py
└── lib
    └── python3.6
        └── site-packages
            ├── python_rapidjson-0.7.2.dist-info
            │   ├── INSTALLER
            │   ├── LICENSE
            │   ├── METADATA
            │   ├── RECORD
            │   ├── top_level.txt
            │   └── WHEEL
            └── rapidjson.cpython-36m-x86_64-linux-gnu.so
```

The content of existing python-rapidjson-0.5.2-py36hf484d3e_1001.tar.bz2:
```
.
├── info
│   ├── about.json
│   ├── files
│   ├── git
│   ├── hash_input.json
│   ├── index.json
│   ├── LICENSE.txt
│   ├── paths.json
│   ├── recipe
│   │   ├── bld.bat
│   │   ├── build.sh
│   │   ├── conda_build_config.yaml
│   │   ├── meta.yaml
│   │   └── meta.yaml.template
│   └── test
│       └── run_test.py
└── lib
    └── python3.6
        └── site-packages
            ├── python_rapidjson-0.5.2-py3.6.egg-info
            │   ├── dependency_links.txt
            │   ├── PKG-INFO
            │   ├── SOURCES.txt
            │   └── top_level.txt
            └── rapidjson.cpython-36m-x86_64-linux-gnu.so
```

So not much changed :)

Out of interest, the content of rapidjson-1.1.0-he1b5a44_1002.tar.bz2:
```
.
├── include
│   └── rapidjson
│       ├── allocators.h
│       ├── document.h
│       ├── encodedstream.h
│       ├── encodings.h
│       ├── error
│       │   ├── en.h
│       │   └── error.h
│       ├── filereadstream.h
│       ├── filewritestream.h
│       ├── fwd.h
│       ├── internal
│       │   ├── biginteger.h
│       │   ├── diyfp.h
│       │   ├── dtoa.h
│       │   ├── ieee754.h
│       │   ├── itoa.h
│       │   ├── meta.h
│       │   ├── pow10.h
│       │   ├── regex.h
│       │   ├── stack.h
│       │   ├── strfunc.h
│       │   ├── strtod.h
│       │   └── swap.h
│       ├── istreamwrapper.h
│       ├── memorybuffer.h
│       ├── memorystream.h
│       ├── msinttypes
│       │   ├── inttypes.h
│       │   └── stdint.h
│       ├── ostreamwrapper.h
│       ├── pointer.h
│       ├── prettywriter.h
│       ├── rapidjson.h
│       ├── reader.h
│       ├── schema.h
│       ├── stream.h
│       ├── stringbuffer.h
│       └── writer.h
├── info
│   ├── about.json
│   ├── files
│   ├── git
│   ├── hash_input.json
│   ├── has_prefix
│   ├── index.json
│   ├── LICENSE.txt
│   ├── paths.json
│   ├── recipe
│   │   ├── bld.bat
│   │   ├── build.sh
│   │   ├── conda_build_config.yaml
│   │   ├── meta.yaml
│   │   └── meta.yaml.template
│   └── test
│       └── run_test.sh
├── lib
│   ├── cmake
│   │   └── RapidJSON
│   │       ├── RapidJSONConfig.cmake
│   │       └── RapidJSONConfigVersion.cmake
│   └── pkgconfig
│       └── RapidJSON.pc
└── share
    └── doc
        └── RapidJSON
            ├── examples
            │   ├── capitalize
            │   │   └── capitalize.cpp
            │   ├── CMakeLists.txt
            │   ├── condense
            │   │   └── condense.cpp
            │   ├── filterkey
            │   │   └── filterkey.cpp
            │   ├── filterkeydom
            │   │   └── filterkeydom.cpp
            │   ├── jsonx
            │   │   └── jsonx.cpp
            │   ├── messagereader
            │   │   └── messagereader.cpp
            │   ├── parsebyparts
            │   │   └── parsebyparts.cpp
            │   ├── pretty
            │   │   └── pretty.cpp
            │   ├── prettyauto
            │   │   └── prettyauto.cpp
            │   ├── schemavalidator
            │   │   └── schemavalidator.cpp
            │   ├── serialize
            │   │   └── serialize.cpp
            │   ├── simpledom
            │   │   └── simpledom.cpp
            │   ├── simplereader
            │   │   └── simplereader.cpp
            │   ├── simplewriter
            │   │   └── simplewriter.cpp
            │   └── tutorial
            │       └── tutorial.cpp
            └── readme.md
```

So no clobber errors. This is afaik expected as rapidjson is a header only lib and does not provide its own compiled lib.

**Comment by dbast** [comment]
@hajapy Can you have a look again? Thx.

**Comment by hajapy** [comment]
Fantastic! Thanks for this nice work!

**Pull request merged**
